baseURL = "https://codecreative.io/"
languageCode = "en-us"
title = "CodeCreative | A ServiceNow Blog"
theme = "codecreative"
pygmentsCodefences = true
pygmentsUseClasses=true

[params]
  author = "Travis Toulson"
  mainSections = ["blog", "docs"]
  dateFormat8601 = "2006-01-02T15:04:05Z0700"

[taxonomies]
  year = "years"
  "note tag" = "notebook/tags"

[markup.goldmark.renderer]
  unsafe= true

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "notebook/tags"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10